name: Build and deploy Node.js app to Azure Web App - AWAP-MovieApp-Backend

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Navigate to the server folder and install dependencies
        run: |
          cd server
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "development"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: "Create .env file"
        run: |
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        working-directory: server

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_92B1F2FCE3E443F59006A08BD1170A5A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2D931CD518824F3EBF3AD6F6278AD1A1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FDAC5C24B6B3402B9A03D468F8A74AB6 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "AWAP-MovieApp-Backend"
          slot-name: "Production"
          package: ./server

      - name: Clean up .env file
        run: rm .env
        working-directory: server
